### ISSUE TITLE
Upgrade to bootstrap alpha 3

### ISSUE THREAD

**Issue by djhi** [marmelab/javascript-boilerplate#112]

**Comment by Kmaschta** [comment]
IMO we shouldn't lock our boilerplat with bootstrap.

**Comment by djhi** [comment]
Can you give more details ?

**Comment by djhi** [comment]
Don't forget that bootstrap 3 (and all other frameworks for that matter) don't provide just the css: they also "impose" the html structure. If we have a frontend in our boilerplate, we have to make a choice.

Being framework agnostic would be great but I fail to see how we could achieve that.

**Comment by Kmaschta** [comment]
Flexbox and CSS3 allow us to manage columns and most of bootstrap features.

Moreover, if we think in terms of React components:
- all components should (or will?) give an styling API that will let us compose the style at hight level
- even if a component is about isolation and not always reutilization, a component should not require something else that itself to work 
- `col-md-5` does not describe what is the element but how it fit in its parent (if its parent is the row)
- `col-xs-12 col-sm-12 col-md-2 col-lg-2` on all div is too big! And it's sadly required for real app with bootstrap

Personally, I don't really like bootstrap for some reasons, but more objectively: if we want to take a style framework, we should have the ability to choose a lighter framework like [Spectre.css](https://picturepan2.github.io/spectre/) or something different like [Material UI](http://www.material-ui.com/).

**Comment by djhi** [comment]
That's a thourough answer :)

About the two last points. IMO the prb is not the framework but our current usage of it. If we keep the bootstrap html structure, we should declare CSS classes which describe the element but (with sass or any other pre processor) which uses the bootstrap features. For example:

```sass
.home {
    @extends .col-xs-12;
    @extends .col-sm-12;
    @extends col-md-2;
    @extends .col-lg-2;
}
```

You still benefits from the built in features of bootstrap but have real describing classes for your usage (easier e2e testing, etc.) and don't have those ugly multiple classes in your jsx code. Moreover, you can then use whatever bootstrap theme easily and users are already well aware of bootstrap components.

I agree we should consider something else like material UI (but not in its current state, I suggest we wait for the next refactoring), or react-bootstrap or [reactstrap](https://reactstrap.github.io/) (my current choice on a personal project. I'm not fond of boostrap as we have to include jquery or tether to have simple components like dropdown working. 

I think we should investigate the different react libraries for styling:
- [aphrodite](https://github.com/Khan/aphrodite)
- [radium](http://stack.formidable.com/radium/)
- [css-modules](https://github.com/css-modules/css-modules)

What I'm against to is having a new marmelab library of components we use in all our apps.

**Comment by djhi** [comment]
Some data: https://github.com/MicheleBertoli/css-in-js

PS: about why I'm against having a library of components
There are already plenty of them as listed previously (and there are a lot more) and we already have lots of OSS projects to maintain. Finally, I think this is not where we can provide value to our customers.

**Comment by Kmaschta** [comment]
You're right, we don't need to reinvent the wheel.
I think we miss the best practices in the field "component styling", I've just asked @fzaninotto not long ago if we should use react `StyleSheet` or only CSS and `className`.

:+1: for the investigations and research, I'll read this later.
Keep digging!

**Comment by djhi** [comment]
Another interesting project: [fela.js](http://fela.js.org/)

**Comment by djhi** [comment]
Upgraded to bootstrap alpha 5.
