### ISSUE TITLE
Fields on the Frontend and Admin sign in pages lose focus

### ISSUE THREAD

**Issue by askrht** [marmelab/javascript-boilerplate#141]
Password field on the Admin Sign in page loses focus after the first character is entered. You have to click it again to continue to enter the password. This was observed in Chrome for Windows and in Chrome for Linux.

**Comment by Kmaschta** [comment]
I was the same issue but wasn't sure it was caused by the app or a chrome extension.

**Comment by djhi** [comment]
Yes I noticed it too. I think it's related to the redux form validation. The same behavior happens on the email field. To reproduce: make it fail validation then fix it.

**Comment by askrht** [comment]
@Kmaschta @djhi your inputs, an explanation by @erikras in this Github [issue](https://github.com/erikras/redux-form/issues/1094) and the [documentation](http://redux-form.com/6.1.1/docs/MigrationGuide.md/) for migrating to the new version of redux-form have helped me to identify and isolate the root cause.

I am able to solve the identical problem on  `frontend` by modifying the `renderInput` function. like so,

```
import classNames from 'classnames';
import React from 'react';
import FormGroup from '../ui/FormGroup';

export default (field) => {
    // debugger;
    const { meta: { touched, error }, id ,label } = field;

    return (
        <FormGroup key={field.name} field={field}>
            <label className="col-form-label" htmlFor={id}>{label}</label>
            <input
                {...{ ...field.input, id }}
                className={classNames('form-control input-lg', {
                    'form-control-danger': touched && error && error.length > 0,
                    'form-control-success': touched && (!error || error.length === 0),
                })}
                type={field.type}
            />
        </FormGroup>
    );
};
```
and the form fields in SignIn.js, like so:

```
<Field
    name="email"
    component={renderInput}
    type="email"
    id='signin_email'
    label='Email'
/>
<Field
    name="password"
    component={renderInput}
    type="password"
    id='signin_password'
    label='Password'
/>
```
If you permit, I would like to contribute a pull request after patching and testing `SignIn` and `SignUp` pages in both `admin` and `frontend` user interfaces.

Happy Thanksgiving!

**Comment by djhi** [comment]
Hi! Sure, we would happily review a PR for this :) thanks @askrht

**Comment by askrht** [comment]
Submitted a pull request to merge the fixes.
