### ISSUE TITLE
api server not streaming logs to console

### ISSUE THREAD

**Issue by lucidsif** [marmelab/javascript-boilerplate#146]
Whether a request to the api server is successful or not, nothing is being streamed to the console (using the command "make log-api-dev" after starting the apps with pm2 using "make run-dev".  I am able to stream logs to the console from the frontend server, but not the api server. I am a novice developer so perhaps there is something I am missing so I apologize for that. I spent hours trying to stream logs from the api server to the console with no success.

**Comment by djhi** [comment]
Did you run the `make install` command first ? It should have created a `config/development.js` file with the logger configuration overrided for development environment. I do have logs when running `make log-api-dev`

**Comment by lucidsif** [comment]
I don't remember if I did, but I thought I did. I checked and saw a `config/development-dist.js` file with the logger configuration object `http: { Console: { timestamp: true, colorize: true }}`. I copied this into config/default.js. I now see logs!! Thank you for the quick response and great project!

**Comment by djhi** [comment]
No you should copy it as `development.js`. It's content will be used by `node-config` to override some of the `default.js` contents. Please refer to `node-config` documentation

**Comment by djhi** [comment]
If you overwrite `default.js`, you'll loose all the other parameters which were not overridden in `development.js` and the application won't work

**Comment by lucidsif** [comment]
Ok, I understand now. Thank you for letting me know.
