### ISSUE TITLE
Running on Cloud9, change API port

### ISSUE THREAD

**Issue by portokallidis** [marmelab/javascript-boilerplate#37]
Great stuff again!
I am trying to run this on the Cloud9 infrastructure.
Is there any simple way for making :3000 -> :8080/api ?

**Comment by djhi** [comment]
I don't think so, the 8080 port is used by webpack-dev-server

**Comment by portokallidis** [comment]
So ok maybe i could change the api from to :3000 -> :8081
Thank for the quick response i will provide info for others what will search for Cloud9
Cloud 9 Available ports:
8080 -> https://<workspacename>-<username>.c9users.io
8081 -> https://<workspacename>-<username>.c9users.io:8081
8082 -> https://<workspacename>-<username>.c9users.io:8082

**Comment by Kmaschta** [comment]
You can change the API port with the `NODE_PORT` env variable.

Do not forget to add it into `config/pm2_servers/dev.json` if you want to use pm2.

**Comment by djhi** [comment]
We should add a wiki for things like this

**Comment by fzaninotto** [comment]
Better: write it in the Readme
