### ISSUE TITLE
Should we use babel-transformer, or the babel-node command?

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/javascript-boilerplate#4]

**Comment by jeromemacias** [comment]
:+1: for the `babel-node` command, all is configurable into `.babelrc`.

**Comment by djhi** [comment]
test githubhook (sorry)

**Comment by Kmaschta** [comment]
Babel-node is not recommended for production, [due to its memory usage](https://babeljs.io/docs/usage/cli/#babel-node).
