### ISSUE TITLE
Add functional tests on the frontend

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/javascript-boilerplate#40]
Using Selenium and Nightwatch

**Comment by djhi** [comment]
I tried to make them pass on travis for almost 2 days. Functional tests are passing locally but I can't figure out why they don't on travis. I ended up commenting them...

**Comment by fzaninotto** [comment]
Did you try switching nightmare with phantomjs or Chrome?

**Comment by djhi** [comment]
I tried chrome, not phantomjs. It might be worth testing it too

**Comment by Kmaschta** [comment]
#58 closes this issue with selenium, nightwatch and chromium.
