### ISSUE TITLE
Add default limit and offset for `selectPage` method

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/javascript-boilerplate#52]
In [selectPage](https://github.com/marmelab/javascript-boilerplate/blob/master/src/api/lib/db/queries/selectPage.js#L17), there is a dangerous behavior: API may return all records if neither `limit` nor `offset` is specified. This issue, coupled with #51 makes the API to return all available records. It doesn't scale well. :)

We should add a default value for these two parameters. This way, even if we want to retrieve **all** records, we would need to specify it by hand, setting a `limit = 0` for instance.

**Comment by fzaninotto** [comment]
:+1:
