### ISSUE TITLE
Webpack hot reloader not working (reload page)

### ISSUE THREAD

**Issue by GuillaumeCisco** [marmelab/javascript-boilerplate#89]
Hello, just pulled your repository.
I tried to test webpack hot reloading but without success.
The HotModule reloads all the page when I change a character in source files.

Here is a screen:
![screenshot_2016-04-13_18-51-30](https://cloud.githubusercontent.com/assets/1155244/14502936/14d8e28e-01ae-11e6-9d3c-6c48a3dcf56f.png)

**Comment by GuillaumeCisco** [comment]
Further informations. It looks like this error is caused by webpack dev server used in cli mode.
I tried using webpack with react-hot-loader and the node api and it works like a charm ;)

**Comment by djhi** [comment]
Should be fixed now. Thanks for reporting this issue

**Comment by GuillaumeCisco** [comment]
Further information, I had to use Webpack Dev Server API and the watch-poll settings as written in the doc.
Hope, it will help for further unexpected regressions.
